name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yml@main

  test:
    uses: analect-io/.github/.github/workflows/test.yml@main

  quality-gate:
    uses: analect-io/.github/.github/workflows/sonarqube.yml@main
    secrets: inherit

  build-and-push:
    uses: analect-io/.github/.github/workflows/build-and-push.yml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - test
      - quality-gate

  security-gateway:
    uses: analect-io/.github/.github/workflows/trivy.yml@main
    needs:
      - build-and-push

  deploy:
    uses: analect-io/.github/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env
      - security-gateway

  notify:
    uses: analect-io/.github/.github/workflows/notify.yml@main
    if: always()
    secrets: inherit
    needs:
      - deploy