name: Snyk Golang 🔒

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
jobs:
  security:
    name: Security Scan 🔒
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
