name: Test Application 🔬

on:
  workflow_call:

jobs:
  test:
    name: Test Application 🔬
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Run Tests 🧪
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: ./docker-compose.yml
          service: test