name: Test Golang 🔎

on:
  workflow_call:

jobs:
  test:
    name: Test Application 🔎
    runs-on: ubuntu-latest
    needs:
      - vars
    strategy:
      matrix:
        go: ["1.17", "1.18"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version:
      - run: go test -v ./...