name: Trivy Scan 🔒

on:
  workflow_call:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner 🔎
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ needs.env.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security Tab 📈
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'